[package]
name = "hub"
version = "0.3.0"
description = "Central hub for oodx/RSB ecosystem - dependency management and global utilities"
license = "AGPL-3.0"
repository = "https://github.com/oodx/hub"
edition = "2021"

[features]
default = []

# Individual dependency features
base64 = ["dep:base64"]
chrono = ["dep:chrono"]
glob = ["dep:glob"]
lazy_static = ["dep:lazy_static"]
libc = ["dep:libc"]
portable-pty = ["dep:portable-pty"]
rand = ["dep:rand"]
regex = ["dep:regex"]
serde = ["dep:serde"]
serde_json = ["dep:serde_json"]
urlencoding = ["dep:urlencoding"]
uuid = ["dep:uuid"]

# Domain-based feature groups
text = ["regex", "lazy_static", "unicode-width"]
data = ["serde", "serde_json", "base64"]
time = ["chrono", "uuid"]
web = ["urlencoding"]
system = ["libc", "glob"]
dev = ["portable-pty"]
random = ["rand"]

# Convenience feature groups
common = ["text", "data", "criterion", "thiserror", "tempfile"]
core = ["text", "data", "time"]
extended = ["text", "data", "time", "web", "system"]
all = ["text", "data", "time", "web", "system", "dev", "random"]

# Legacy compatibility with RSB deps- naming
deps-base64 = ["base64"]
deps-chrono = ["chrono"]
deps-glob = ["glob"]
deps-lazy_static = ["lazy_static"]
deps-libc = ["libc"]
deps-rand = ["rand"]
deps-regex = ["regex"]
deps-serde = ["serde"]
deps-serde_json = ["serde_json"]
deps-urlencoding = ["urlencoding"]
deps-uuid = ["uuid"]

deps-all = [
    "deps-base64",
    "deps-chrono",
    "deps-glob",
    "deps-lazy_static",
    "deps-libc",
    "deps-rand",
    "deps-regex",
    "deps-serde",
    "deps-serde_json",
    "deps-urlencoding",
    "deps-uuid",
]

# Convenience alias for the full set (RSB compatibility)
deps = ["deps-all"]

unicode-width = ["dep:unicode-width"]
criterion = ["dep:criterion"]
thiserror = ["dep:thiserror"]
tempfile = ["dep:tempfile"]
[dependencies]
# Core external dependencies - versions managed centrally
base64 = { version = "0.22.1", optional = true }
chrono = { version = "0.4.42", features = ["serde"], optional = true }
glob = { version = "0.3.3", optional = true }
lazy_static = { version = "1.5.0", optional = true }
libc = { version = "0.2.175", optional = true }
portable-pty = { version = "0.9", optional = true }
rand = { version = "0.9.2", optional = true }
regex = { version = "1.11.2", optional = true }
serde = { version = "1.0.226", features = ["derive"], optional = true }
serde_json = { version = "1.0.145", optional = true }
urlencoding = { version = "2.1.3", optional = true }
uuid = { version = "1.18.1", features = ["v4"], optional = true }
unicode-width = { version = "0.2.1", optional = true }
criterion = { version = "0.7.0", optional = true }
thiserror = { version = "2.0.16", optional = true }
tempfile = { version = "3.22.0", optional = true }

[dev-dependencies]
# Development tools for testing cargohold itself
assert_cmd = "2.0"
predicates = "3.0"

[lib]
name = "hub"
path = "src/lib.rs"

[package.metadata.hub]
# Custom hub metadata section for hub configuration
