[package]
name = "prontodb"
version = "0.7.0"
edition = "2021"
description = "ProntoDB — namespaced, file-based KV on SQLite with RSB-style CLI"
license = "Apache-2.0"
repository = "https://github.com/oodx/prontodb"

[dependencies]
anyhow = "1"
atty = "0.2"                                       # TTY detection for pipe input
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
directories = "6"
md5 = "0.7"                                        # Content hashing for cache keys
rusqlite = { version = "0.37" }                    # default: link to system SQLite
rsb = { path = "../rsb" }  # Use local version with XDG fixes
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
tempfile = "3"
xstream = { path = "../xstream", optional = true } # XStream integration



# Optional value-layer features
zstd = { version = "0.13", optional = true }       # compression-zstd
aes-gcm = { version = "0.10", features = ["aes"], optional = true }  # encryption
pbkdf2 = { version = "0.12", optional = true }
sha2 = { version = "0.10", optional = true }
rand = { version = "0.9.2", optional = true }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"

[features]
default = ["json", "sqlite-bundled"]               # Include bundled SQLite for easy builds  
json = ["dep:serde", "dep:serde_json"]
streaming = ["dep:xstream"]                        # XStream integration for advanced streaming
pipe-cache = []                                    # Revolutionary pipe cache with zero data loss

# Use system SQLite by default. If you want portability, build with:
#   cargo build --features sqlite-bundled
sqlite-bundled = ["rusqlite/bundled"]

compression-zstd = ["dep:zstd"]
encryption-aes   = ["dep:aes-gcm", "dep:pbkdf2", "dep:sha2", "dep:rand"]
