[package]
name = "prontodb"
version = "0.1.0"
edition = "2021"
description = "ProntoDB — namespaced, file-based KV on SQLite with RSB-style CLI"
license = "MIT"
repository = "https://github.com/oodx/prontodb"

[dependencies]
anyhow = "1"
base64 = "0.22"
directories = "5"
rusqlite = { version = "0.32" }                    # default: link to system SQLite
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

# RSB framework/macros (using your repo URL; assumes the RSB crate(s) are exported from that workspace)
rsb = { git = "https://github.com/oodx/rebel", branch = "main" }

# Optional value-layer features
zstd = { version = "0.13", optional = true }       # compression-zstd
aes-gcm = { version = "0.10", features = ["aes256"], optional = true }  # encryption
pbkdf2 = { version = "0.12", optional = true }
sha2 = { version = "0.10", optional = true }
rand = { version = "0.8", optional = true }

[features]
default = ["json"]                                  # you said JSON is divine → enable by default
json = ["dep:serde", "dep:serde_json"]

# Use system SQLite by default. If you want portability, build with:
#   cargo build --features sqlite-bundled
sqlite-bundled = ["rusqlite/bundled"]

compression-zstd = ["dep:zstd"]
encryption-aes   = ["dep:aes-gcm", "dep:pbkdf2", "dep:sha2", "dep:rand"]
